services:
  scraper:
    container_name: OLX_scraper
    build: .
    volumes:
      - ./:/app
    restart: always
    environment:
      - DOCKER_ENV=true
      - TZ=America/Recife
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - USE_GPU=true
    gpus: all

